import 'dart:io';
import 'dart:typed_data';

import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

/// Helper that saves backend-generated document bytes to a temporary file and
/// exposes native "open" and "share" actions.
///
/// The authoritative document (PDF, Excel, packing list, invoice, receipt,
/// shipping label) is generated by the backend; the mobile app never
/// recalculates totals, currency, commissions, CBM, etc.
class DocumentHandler {
  const DocumentHandler._();

  /// Saves [bytes] to a temporary file named [fileName] and returns the path.
  static Future<String> saveToTemp({
    required Uint8List bytes,
    required String fileName,
  }) async {
    final dir = await getTemporaryDirectory();
    final safeName = _sanitizeFileName(fileName);
    final file = File('${dir.path}${Platform.pathSeparator}$safeName');
    await file.writeAsBytes(bytes, flush: true);
    return file.path;
  }

  /// Opens the document with the device's default app for its type.
  static Future<OpenResult> open(String path) => OpenFilex.open(path);

  /// Shares the document via the platform share sheet.
  static Future<void> shareFile({
    required String path,
    required String fileName,
    String? subject,
    String? text,
  }) async {
    final xFile = XFile(path, name: fileName);
    await Share.shareXFiles(
      [xFile],
      subject: subject,
      text: text,
    );
  }

  /// Convenience: download bytes are already in hand; save then open.
  static Future<OpenResult> saveAndOpen({
    required Uint8List bytes,
    required String fileName,
  }) async {
    final path = await saveToTemp(bytes: bytes, fileName: fileName);
    return open(path);
  }

  /// Convenience: download bytes are already in hand; save then share.
  static Future<void> saveAndShare({
    required Uint8List bytes,
    required String fileName,
    String? subject,
    String? text,
  }) async {
    final path = await saveToTemp(bytes: bytes, fileName: fileName);
    await shareFile(path: path, fileName: fileName, subject: subject, text: text);
  }

  static String _sanitizeFileName(String name) {
    final cleaned = name
        .replaceAll(RegExp(r'[\\/:*?"<>|\r\n\t]'), '_')
        .trim();
    if (cleaned.isEmpty) return 'document';
    return cleaned;
  }
}
