// Generated from Sahajomy-Mobile-App/GENERATED_SCREEN_INVENTORY.md.
// Regenerate with: .\tool\generate_app_route_aliases.ps1
const appRouteAliases = <String, String>{
  '/agent/batches/:batchId/packing-lists/new': 'agent-create-packing-list.html',
  '/agent/batches/:batchId/financials': 'agent-batch-financials.html',
  '/cargo/documentationworkspace/warehouse-automation':
      'cargo-admin-warehouse-automation.html',
  '/cargo/documentationworkspace/manual-cargo-intake':
      'cargo-admin-manual-intake.html',
  '/cargo/documentationworkspace/packing-lists':
      'cargo-admin-packing-lists.html',
  '/cargo/documentationworkspace/customers':
      'cargo-admin-documentation-customers.html',
  '/cargo/settings/staff-branches': 'cargo-admin-staff-branches.html',
  '/cargo/settings/billing': 'cargo-admin-billing-usage.html',
  '/cargo/containers/new': 'cargo-admin-container-management.html',
  '/agent/batches/new': 'agent-create-batch.html',
  '/customer/shipment-orders/:shipmentOrderId':
      'customer-shipment-order-detail.html',
  '/customer/sea-bookings/:seaBookingId': 'customer-sea-booking-detail.html',
  '/agent/packing-lists/:packingListId': 'agent-packing-list-detail.html',
  '/customer/warehouse-access/:token': 'customer-warehouse-parcels.html',
  '/agent/containers/:containerId': 'agent-container-detail.html',
  '/admin/operators/:operatorId': 'super-admin-operator-detail.html',
  '/admin/companies/:companyId': 'super-admin-company-detail.html',
  '/customer/orders/:orderId': 'customer-order-details.html',
  '/label/sea/:seaBookingId': 'shared-sea-shipping-label.html',
  '/agizisha/agents/:handle': 'public-agizisha-agent-storefront.html',
  '/agent/batches/:batchId': 'agent-batch-details.html',
  '/agent/orders/:orderId': 'agent-order-detail.html',
  '/agizisha/product/:id': 'public-agizisha-product-detail.html',
  '/label/air/:bookingId': 'shared-air-shipping-label.html',
  '/admin/users/:userId': 'super-admin-user-details.html',
  '/cargo/documentationworkspace': 'cargo-admin-documentation-workspace.html',
  '/customer/express-air-cargo': 'customer-express-air-cargo.html',
  '/agent/agizisha-storefront': 'agent-storefront.html',
  '/customer/track-shipments': 'customer-shipment-tracking.html',
  '/customer/china-addresses': 'customer-china-addresses.html',
  '/admin/pending-approvals': 'super-admin-approvals.html',
  '/agent/express-air-cargo': 'agent-express-air-cargo.html',
  '/sourcing-agent/register': 'public-sourcing-agent-registration.html',
  '/cargo-operator/register': 'public-cargo-company-registration.html',
  '/cargo/express-air-cargo': 'cargo-admin-express-air-cargo.html',
  '/agent/pending-approval': 'agent-pending-approval.html',
  '/cargo/pending-approval': 'cargo-admin-pending-approval.html',
  '/customer/sea-bookings': 'customer-sea-bookings.html',
  '/cargo/track-shipments': 'cargo-admin-track-shipment.html',
  '/agent/china-addresses': 'agent-china-addresses.html',
  '/cargo/shipment-orders': 'cargo-admin-shipment-orders.html',
  '/agent/track-shipments': 'agent-track-shipment.html',
  '/admin/track-shipments': 'super-admin-track-shipment.html',
  '/admin/sourcing-agents': 'super-admin-sourcing-agents.html',
  '/agent/agizisha-orders': 'agent-agizisha-orders.html',
  '/admin/subscriptions': 'super-admin-subscriptions.html',
  '/agent/packing-lists': 'agent-packing-lists.html',
  '/customer/containers': 'customer-search-container.html',
  '/account/workspaces': 'shared-workspace-selection.html',
  '/customer/dashboard': 'customer-dashboard.html',
  '/admin/reservations': 'super-admin-reservations.html',
  '/cargo/fcl-requests': 'cargo-admin-fcl-requests.html',
  '/cargo/sea-bookings': 'cargo-admin-sea-bookings.html',
  '/agent/sea-bookings': 'agent-sea-bookings.html',
  '/public/containers': 'public-containers.html',
  '/customer/agizisha': 'customer-agizisha.html',
  '/admin/commission': 'super-admin-commission.html',
  '/cargo/containers': 'cargo-admin-container-management.html',
  '/admin/audit-logs': 'super-admin-platform-activity.html',
  '/agent/containers': 'agent-containers.html',
  '/cargo/warehouses': 'cargo-admin-warehouses.html',
  '/agent/financials': 'agent-financials.html',
  '/support/tickets': 'public-support-tickets.html',
  '/admin/companies': 'super-admin-companies.html',
  '/agent/dashboard': 'agent-dashboard.html',
  '/admin/dashboard': 'super-admin-dashboard.html',
  '/cargo/dashboard': 'cargo-admin-dashboard.html',
  '/customer/orders': 'customer-orders.html',
  '/admin/operators': 'super-admin-operators.html',
  '/admin/bookings': 'super-admin-bookings.html',
  '/cargo/receipts': 'cargo-admin-receipts.html',
  '/cargo/finance': 'cargo-admin-financial-analytics.html',
  '/agent/batches': 'agent-batches.html',
  '/admin/goods': 'super-admin-goods-classification.html',
  '/admin/users': 'super-admin-user-management.html',
  '/warehouses/:warehouseSlug': 'public-warehouse-detail.html',
  '/product/:productId': 'shared-product-detail.html',
  '/shared/:token': 'public-shared-batch.html',
  '/china-sourcing-africa': 'public-china-sourcing-africa.html',
  '/sea-freight-africa': 'public-sea-freight-africa.html',
  '/fcl-quote-request': 'public-fcl-quote-request.html',
  '/air-cargo-africa': 'public-air-cargo-africa.html',
  '/staff-invitation': 'public-staff-invitation.html',
  '/verify-receipt': 'public-receipt-verification.html',
  '/accessibility': 'public-accessibility.html',
  '/how-it-works': 'public-how-it-works.html',
  '/warehouses': 'public-warehouses.html',
  '/air-cargo': 'public-air-cargo.html',
  '/agizisha': 'public-agizisha-catalogue.html',
  '/feedback': 'public-feedback.html',
  '/cookies': 'public-cookies.html',
  '/pricing': 'public-pricing.html',
  '/sitemap': 'public-sitemap.html',
  '/contact': 'public-contact.html',
  '/privacy': 'public-privacy.html',
  '/support': 'public-support.html',
  '/login': 'customer-login.html',
  '/about': 'public-about.html',
  '/legal': 'public-legal.html',
  '/terms': 'public-terms.html',
  '/faq': 'public-faq.html',
  '/': 'public-landing.html',
  '/customer/notifications': 'customer-notifications.html',
  '/customer/reservations': 'customer-reservations.html',
  '/customer/profile': 'customer-profile.html',
  '/customer/documents': 'customer-documents.html',
  '/customer/track-shipment': 'customer-shipment-tracking.html',
};
