"""Immutable WCO HS 2022 based platform catalogue used by the rollout migration.

The platform family is intentionally broader than a customs declaration. Importers
must still provide the precise commodity description and destination-country tariff
line when declaring goods.
"""

STANDARD_VERSION = "HS 2022"

CATEGORIES = [
    "Agriculture and Animal Equipment",
    "Food and Animal Feed",
    "Textiles and Apparel",
    "Footwear and Travel Goods",
    "Cosmetics and Personal Care",
    "Electronics and ICT",
    "Vehicles and Transport Equipment",
    "Machinery and Industrial Equipment",
    "Home, Furniture and Decor",
    "Kitchen and Household Articles",
    "Hardware and Construction",
    "Packaging and Paper",
    "Medical and Chemicals",
    "Toys, Sports and Recreation",
    "Jewellery and Personal Accessories",
    "Stationery and Office Supplies",
]


def item(category, name, hs_reference, hs_level, *aliases):
    return {
        "category": category,
        "name": name,
        "hs_reference": hs_reference,
        "hs_level": hs_level,
        "aliases": list(aliases),
    }


CATALOG = [
    item(
        "Agriculture and Animal Equipment",
        "Poultry and Livestock Equipment",
        "8436",
        "heading",
        "Chicken Cages",
        "Animal Pots",
    ),
    item(
        "Agriculture and Animal Equipment",
        "Poultry Incubators",
        "843621",
        "subheading",
        "Incubator",
    ),
    item(
        "Agriculture and Animal Equipment",
        "Fertilizers",
        "31",
        "chapter",
        "Fertilizers",
    ),
    item(
        "Agriculture and Animal Equipment",
        "Agricultural and Horticultural Hand Tools",
        "8201",
        "heading",
        "Tools",
    ),
    item(
        "Food and Animal Feed", "Prepared Animal Feed", "2309", "heading", "Fish Food"
    ),
    item(
        "Food and Animal Feed",
        "Food Preparations",
        "21",
        "chapter",
        "Food Stuff",
        "Sundries",
    ),
    item(
        "Textiles and Apparel",
        "Children's Clothing",
        "6111/6209",
        "multiple",
        "Baby/Children Clothes",
    ),
    item(
        "Textiles and Apparel",
        "Textile Fabrics",
        "50-60",
        "multiple",
        "Clothes Material",
        "Kitenge",
    ),
    item(
        "Textiles and Apparel",
        "Articles of Apparel",
        "61-62",
        "multiple",
        "Ready Made Garments",
    ),
    item("Textiles and Apparel", "Bed Linen", "6302", "heading", "Bed Sheets"),
    item("Textiles and Apparel", "Headgear", "6505", "heading", "Caps"),
    item("Textiles and Apparel", "Ties and Bow Ties", "6215", "heading", "Ties"),
    item("Textiles and Apparel", "Scarves and Shawls", "6214", "heading", "Scarf"),
    item("Textiles and Apparel", "Used Clothing", "6309", "heading", "Bales"),
    item("Textiles and Apparel", "Textile Yarn", "50-55", "multiple", "Fabric Yarn"),
    item(
        "Textiles and Apparel",
        "Sewing and Tailoring Materials",
        "50-63",
        "multiple",
        "Tailoring Material",
    ),
    item(
        "Footwear and Travel Goods",
        "Diapers and Sanitary Articles",
        "9619",
        "heading",
        "Baby Diapers",
    ),
    item(
        "Footwear and Travel Goods",
        "Handbags, Clutches and Wallets",
        "4202",
        "heading",
        "Lady Bags",
        "Clutches",
        "Wallets",
    ),
    item(
        "Footwear and Travel Goods",
        "Travel Bags and Luggage",
        "4202",
        "heading",
        "Travelling Bags",
    ),
    item(
        "Footwear and Travel Goods",
        "Packing Sacks and Bags",
        "6305",
        "heading",
        "Non Woven Bags",
    ),
    item(
        "Footwear and Travel Goods",
        "Footwear",
        "64",
        "chapter",
        "All Shoes",
        "Slippers",
    ),
    item(
        "Cosmetics and Personal Care",
        "Beauty and Skin Care Preparations",
        "3304",
        "heading",
        "Cosmetics",
    ),
    item(
        "Cosmetics and Personal Care",
        "Perfumes and Toilet Waters",
        "3303",
        "heading",
        "Perfume",
    ),
    item(
        "Cosmetics and Personal Care",
        "Soap and Cleansing Preparations",
        "3401",
        "heading",
        "Soap",
    ),
    item(
        "Cosmetics and Personal Care",
        "Wigs and Hairpieces",
        "6704",
        "heading",
        "Wigs Models",
    ),
    item(
        "Cosmetics and Personal Care",
        "Hair Accessories",
        "9615",
        "heading",
        "Hair Accessories",
    ),
    item(
        "Cosmetics and Personal Care",
        "Electric Hair Care Appliances",
        "851632",
        "subheading",
        "Hair Machines",
    ),
    item("Electronics and ICT", "Computers", "8471", "heading", "Laptop/Desktop"),
    item(
        "Electronics and ICT",
        "Computer Parts and Accessories",
        "8473",
        "heading",
        "Accessories",
    ),
    item(
        "Electronics and ICT",
        "Insulated Electric Cables",
        "8544",
        "heading",
        "Network Cables",
    ),
    item(
        "Electronics and ICT",
        "Electrical and Electronic Equipment",
        "85",
        "chapter",
        "Electronics",
    ),
    item(
        "Electronics and ICT",
        "Domestic Electrical Appliances",
        "8509/8516",
        "multiple",
        "Electric Appliances",
        "Home Appliance",
        "Home Appliances",
    ),
    item(
        "Electronics and ICT",
        "Electric Motorcycles and Bicycles",
        "871160",
        "subheading",
        "Electric Bike",
    ),
    item(
        "Electronics and ICT",
        "Electrical Lighting Equipment",
        "9405",
        "heading",
        "Electric Lights",
        "Light Decor",
    ),
    item(
        "Electronics and ICT",
        "Solar Photovoltaic Equipment",
        "854143",
        "subheading",
        "Solar Items",
    ),
    item(
        "Electronics and ICT", "Refrigerators and Freezers", "8418", "heading", "Fridge"
    ),
    item(
        "Electronics and ICT",
        "Mobile Phones",
        "8517",
        "heading",
        "Cheap Mobile Phone",
        "Smart Phone",
    ),
    item(
        "Electronics and ICT",
        "Mobile Phone Parts and Accessories",
        "8517",
        "heading",
        "Mobile Accessories",
    ),
    item(
        "Electronics and ICT",
        "Portable Electric Batteries",
        "8507",
        "heading",
        "Mobile Battery",
        "Battery",
    ),
    item("Electronics and ICT", "Television Receivers", "8528", "heading", "TV"),
    item(
        "Electronics and ICT",
        "Recorded Media",
        "8523",
        "heading",
        "Game CD",
        "Video CD",
    ),
    item(
        "Electronics and ICT",
        "Video Game Equipment",
        "9504",
        "heading",
        "Heavy Games",
        "Light Games",
    ),
    item(
        "Electronics and ICT",
        "Audio and Music Equipment",
        "8518/8519/8527",
        "multiple",
        "Music Equipment",
    ),
    item(
        "Electronics and ICT",
        "Photographic Cameras and Equipment",
        "9006",
        "heading",
        "Photography Equipment",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Motor Vehicle Parts and Accessories",
        "8708",
        "heading",
        "Auto Spare",
        "Car Accessories",
        "Car Spare Parts",
        "Car Spring",
        "Heavy Auto Parts",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Vehicle Lighting and Signalling Equipment",
        "8512",
        "heading",
        "Car Lamp",
        "Car Lights",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Lead-Acid Vehicle Batteries",
        "850710",
        "subheading",
        "Car Battery",
        "Motorcycle Battery",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Motor Vehicle Tyres",
        "4011",
        "heading",
        "Car Tyre",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Motor Vehicle Engines",
        "8407-8408",
        "multiple",
        "Engine",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Lubricating Oils",
        "2710",
        "heading",
        "Engine Oil",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Gearboxes and Parts",
        "870840",
        "subheading",
        "Gear Box",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Oil and Fuel Filters",
        "842123",
        "subheading",
        "Oil Filter",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Motorcycles",
        "8711",
        "heading",
        "Fuel Motorcycle",
    ),
    item(
        "Vehicles and Transport Equipment",
        "Motorcycle Parts and Accessories",
        "871410",
        "subheading",
        "Motorcycle Accessories",
        "Motorcycle Spare Parts",
    ),
    item("Vehicles and Transport Equipment", "Bicycles", "8712", "heading", "Bicycle"),
    item(
        "Vehicles and Transport Equipment",
        "Tractor Parts",
        "8708",
        "heading",
        "Tractor Spare Parts",
    ),
    item(
        "Machinery and Industrial Equipment",
        "Industrial Machinery",
        "84",
        "chapter",
        "Heavy Machines",
        "Electric Machines",
    ),
    item(
        "Machinery and Industrial Equipment",
        "Weighing Machinery",
        "8423",
        "heading",
        "Weighing Machine",
    ),
    item(
        "Machinery and Industrial Equipment",
        "Sewing Machine Parts and Accessories",
        "8452",
        "heading",
        "Sewing Machine Accessories",
    ),
    item(
        "Home, Furniture and Decor",
        "Household Furniture",
        "9403",
        "heading",
        "Home Furniture",
    ),
    item(
        "Home, Furniture and Decor",
        "Office Furniture",
        "9403",
        "heading",
        "Office Furniture",
    ),
    item(
        "Home, Furniture and Decor",
        "Children's Furniture and Baby Walkers",
        "9403",
        "heading",
        "Kids Furniture",
        "Baby Walker",
    ),
    item(
        "Home, Furniture and Decor",
        "Carpets and Textile Floor Coverings",
        "57",
        "chapter",
        "Carpets",
    ),
    item(
        "Home, Furniture and Decor",
        "Artificial Flowers and Foliage",
        "6702",
        "heading",
        "Fake Flowers",
    ),
    item(
        "Home, Furniture and Decor",
        "Picture Frames",
        "4414/8306",
        "multiple",
        "Picture Frames",
    ),
    item("Home, Furniture and Decor", "Wallpaper", "4814", "heading", "Wallpapers"),
    item(
        "Home, Furniture and Decor",
        "Aquariums and Glass Household Articles",
        "7013",
        "heading",
        "Fish Tank",
    ),
    item(
        "Home, Furniture and Decor", "Glass Mirrors", "7009", "heading", "Glass Mirrors"
    ),
    item(
        "Home, Furniture and Decor",
        "Wall Clocks",
        "9105",
        "heading",
        "Watches Wall Clocks",
    ),
    item(
        "Home, Furniture and Decor",
        "Religious and Ceremonial Articles",
        "4420/6913/8306",
        "multiple",
        "Religious Items",
    ),
    item("Home, Furniture and Decor", "Glass Beads", "7018", "heading", "Beads"),
    item(
        "Kitchen and Household Articles",
        "Cooking Appliances",
        "7321/8516",
        "multiple",
        "Cooker",
    ),
    item(
        "Kitchen and Household Articles",
        "Kitchenware and Tableware",
        "3924/6911/6912/7323/7418/7615",
        "multiple",
        "Kitchen Utensils",
        "Kitchenware",
    ),
    item(
        "Hardware and Construction", "Iron or Steel Nails", "7317", "heading", "Nails"
    ),
    item(
        "Hardware and Construction",
        "Caulking Compounds and Sealants",
        "3214",
        "heading",
        "Sealant",
    ),
    item(
        "Hardware and Construction",
        "Ceramic Roofing Tiles",
        "6905",
        "heading",
        "Roof Tiles",
    ),
    item("Hardware and Construction", "Ceramic Tiles", "6907", "heading", "Tiles"),
    item(
        "Hardware and Construction",
        "Metal Roofing Sheets",
        "7210/7212/7308",
        "multiple",
        "Roofing Sheet",
    ),
    item(
        "Hardware and Construction",
        "Paints and Varnishes",
        "3208-3210",
        "multiple",
        "Paint",
    ),
    item(
        "Hardware and Construction",
        "Screws, Bolts and Nuts",
        "7318",
        "heading",
        "Bolt and Nuts",
    ),
    item(
        "Hardware and Construction",
        "General Hardware",
        "73/82/83",
        "multiple",
        "Mixed Heavy Hardware",
        "Mixed Light Hardware",
    ),
    item(
        "Hardware and Construction",
        "Sanitary Ware and Bathroom Fittings",
        "3922/6910/7324",
        "multiple",
        "Toilet Accessories",
    ),
    item(
        "Packaging and Paper",
        "Paper and Paperboard Packaging",
        "4819",
        "heading",
        "Packaging",
        "Paper Bags",
        "Gift Boxes",
    ),
    item(
        "Packaging and Paper",
        "Kraft Paper and Paperboard",
        "4804",
        "heading",
        "Kraft Paper",
    ),
    item(
        "Packaging and Paper",
        "Plastic Packaging Articles",
        "3923",
        "heading",
        "Plastic Bags",
    ),
    item(
        "Medical and Chemicals",
        "Medical and Surgical Instruments",
        "9018",
        "heading",
        "Medical Machines",
        "Hospital Items",
    ),
    item(
        "Medical and Chemicals",
        "Industrial Chemicals",
        "28/29/38",
        "multiple",
        "Chemicals",
    ),
    item(
        "Medical and Chemicals",
        "Protective Face Masks",
        "6307",
        "heading",
        "Medical Masks",
    ),
    item(
        "Toys, Sports and Recreation", "Toys", "9503", "heading", "Toys", "Large Toys"
    ),
    item(
        "Toys, Sports and Recreation",
        "Sports and Fitness Equipment",
        "9506",
        "heading",
        "Gym Equipment",
        "Sports Equipment",
    ),
    item(
        "Toys, Sports and Recreation",
        "Smoking Pipes and Shisha Equipment",
        "9614",
        "heading",
        "Shisha",
    ),
    item(
        "Jewellery and Personal Accessories",
        "Jewellery",
        "7113/7117",
        "multiple",
        "Jewelry",
    ),
    item(
        "Stationery and Office Supplies",
        "Stationery Articles",
        "4820/9608",
        "multiple",
        "Stationeries",
    ),
    item(
        "Stationery and Office Supplies",
        "Printer Toner and Ink Cartridges",
        "8443/3215",
        "multiple",
        "Toner Ink Cartridge",
    ),
]
